## Plugin info!
## Please dont copy this is property of TinyPixelDevz Team!
## Website TinyPixel.ga
## What the Main Title on /wild says!
Name: Teleporting to random Location!
## Small text under title
Text: Make sure to Build Fast!
## world to run the command in 
World: world
## Maximum Wild location on X Cordinate.
max-X-Cord: 3000
## Minimum Wild Location on X Cordinate.
min-X-Cord: 200
## Maximum Wild Location on Y Cordiante.
max-Z-Cord: 3000
## Minimum Wild Location on Y Cordinate.
min-Z-Cord: 200
