## Plugin info!
## Please dont copy this is property of TinyPixelDevz Team!
## Website TinyPixel.ga
## What the Main Title on /wild says!

Name: §a§lTeleporting...

## Small text under title

Text: §4Tiny§aPixel §6>§4>§f Quick! Make a Base!

## world to run the command in 

World: world

## Minimum Wild location on X Cordinate.

minxcord: 200

## Maximum Wild Location on X Cordinate.

maxxcord: 3000

## Minimum Wild Location on Y Cordiante.

minzcord: 200

## Maximum Wild Location on Y Cordinate.

maxzcord: 3000

## Thanks For Downloading CustomWild!
